name: ci

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Go build
      run: go build ./...
    - name: Go test
      run: go test ./...
